### ISSUE TITLE
Question about QC on benchmarking data

### ISSUE THREAD

**Issue by claczny** [gbouras13/hybracter_benchmarking#1]
Dear all,

thanks a lot for the very insightful manuscript and the tool!

When trying to understand the details better to be able to apply the lessons to my own analysis, I saw that the "real" assemblies seem to all include the `--skip_qc` option (https://github.com/gbouras13/hybracter_benchmarking/blob/main/hybracter_benchmarking/workflow/rules/hybracter_real_reads.smk).
When I then looked into the data download instructions (https://github.com/gbouras13/hybracter_benchmarking/blob/main/get_fastqs.md), I could not find how the preprocessing (QC, adapter/barcode trimming, etc.) is done.
I presume that this is done before depositing the ONT (FASTQ) data, correct?
For the Illumina data, I would assume though that the raw reads, i.e., including adapters and low-Q reads, would be remaining in the deposited data.

To give the full picture, I am getting some messages in my current basecalling (including classification of barcodes reads, to be followed by a `dorado demux` step after basecalling) about some reads with unexpected trim intervals during basecalling (https://github.com/nanoporetech/dorado/issues/1149) and I was wondering whether this would be an issue and how this might best be accounted for, e.g., by `hybracter` directly, maybe.

Looking forward to your thoughts!

Thank you very much!

Best wishes and stay safe,

Cedric

**Comment by gbouras13** [comment]
Hi @claczny ,

This is a good question. In terms of the reads, what is on Zenodo will be already qc'd (i.e. filtlong/porechop_abi/fastp for short reads) and subsampled (Rasusa). the reason I used `--skip_qc` for the benchmarking is most assemblers e.g. Unicycler assume you have already qc'd reads (in any case, it usually takes a pretty negligible amount of time). 

If you download the reads from their source (NCBI etc), they won't be qc'd, so I'd run hybracter without `--skip_qc`

Your issue in Dorado is strange! I've never seen that before. I developed hybracter before Dorado (in guppy, QC wasn't automatic) so I built in QC steps. Depending on how you run Dorado, you can now trim adapters and barcodes now (you know more about this than me I assume!) making the porechop_abi part a bit redundant.

In my experience, nanopore reads are pretty robust to "over qc" (i.e. if you ran porechop twice or something), because they are so long, chopping off a few extra bases doesn't really matter downstream. So running them on Dorado data should be completely fine in my view and I would just run Hybracter in its defaults.

Overall, I think you can probably ignore the error if you have enough data with Dorado - if the reads are untrimmed, then porechop should handle it and it only takes a minute or two to run.

If you experiment with and without `--skip_qc` on Dorado reads and get markedly different assemblies, please let me know.

George

**Comment by claczny** [comment]
Hi @gbouras13,

thank you for the explanation. That makes it clearer.
As described in the linked issue in the dorado repository, the disable trimming means that the adapter *and* the barcodes remain. As I understood, `Porechop_ABI` takes care of adapters but not of barcodes.
Hence, I am unsure if there would actually be "over" QC or if some barcodes might remain.
I'd rather play it safe to ensure high quality and as little non-relevant sequences as possible entering into Hybracter :)

Best wishes and stay safe,

Cedric
